# Generated by Django 3.1.12 on 2025-09-25 21:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_userprofile_phone_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='LoginSession',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.CharField(max_length=64, unique=True)),
                ('telegram_user_id', models.CharField(blank=True, max_length=64, null=True)),
                ('phone_number', models.CharField(blank=True, max_length=32, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('is_used', models.BooleanField(default=False)),
                ('ip', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.CharField(blank=True, max_length=256, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='OTPCode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=6)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('attempts', models.PositiveSmallIntegerField(default=0)),
                ('is_verified', models.BooleanField(default=False)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='otp_codes', to='users.loginsession')),
            ],
        ),
        migrations.DeleteModel(
            name='OTPLoginSession',
        ),
        migrations.AddIndex(
            model_name='loginsession',
            index=models.Index(fields=['session_id'], name='users_login_session_4ee494_idx'),
        ),
        migrations.AddIndex(
            model_name='loginsession',
            index=models.Index(fields=['expires_at'], name='users_login_expires_a64231_idx'),
        ),
        migrations.AddIndex(
            model_name='loginsession',
            index=models.Index(fields=['is_used'], name='users_login_is_used_d23e05_idx'),
        ),
        migrations.AddIndex(
            model_name='otpcode',
            index=models.Index(fields=['session', 'is_verified'], name='users_otpco_session_f05851_idx'),
        ),
        migrations.AddIndex(
            model_name='otpcode',
            index=models.Index(fields=['expires_at'], name='users_otpco_expires_10477f_idx'),
        ),
    ]
